version: '3.8'
services:
  app:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=yourdbname
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
